name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version-file: ".python-version"

    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "0.8.22"
        enable-cache: true

    - name: Install frontend dependencies
      working-directory: frontend
      run: bun install

    - name: Build frontend
      working-directory: frontend
      run: bun run build

    - name: Check frontend linting and types
      working-directory: frontend
      run: bun run check

    - name: Install Python dependencies
      run: uv sync --locked --all-extras --dev

    - name: Build Python project
      run: uv build

    - name: Run ruff linting
      run: uv run ruff check

    - name: Run ruff formatting check
      run: uv run ruff format --check